/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ignite.models;

import ignite.datasource.DataSourceFactory;

import java.sql.*;
import java.util.*;

import javax.sql.DataSource;

import org.apache.ignite.cache.*;
import org.apache.ignite.cache.store.jdbc.*;
import org.apache.ignite.configuration.*;
import org.h2.jdbcx.JdbcDataSource;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

/**
 * CacheConfig definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 08/19/2016.
 */
public class CacheConfig {
    /**
     * Create JDBC type for person.
     *
     * @param cacheName Cache name.
     * @return Configured JDBC type.
     */
    private static JdbcType jdbcTypePerson(String cacheName) {
        JdbcType jdbcType = new JdbcType();

        jdbcType.setCacheName(cacheName);
        jdbcType.setDatabaseSchema("ignite");
        jdbcType.setDatabaseTable("person");
        jdbcType.setKeyType("ignite.models.PersonKey");
        jdbcType.setValueType("ignite.models.Person");

        // Key fields for person.
        Collection<JdbcTypeField> keys = new ArrayList<>();
        keys.add(new JdbcTypeField(Types.INTEGER, "age", Integer.class, "age"));
        jdbcType.setKeyFields(keys.toArray(new JdbcTypeField[keys.size()]));

        // Value fields for person.
        Collection<JdbcTypeField> vals = new ArrayList<>();
        vals.add(new JdbcTypeField(Types.INTEGER, "age", Integer.class, "age"));
        vals.add(new JdbcTypeField(Types.VARCHAR, "name", String.class, "name"));
        vals.add(new JdbcTypeField(Types.VARCHAR, "address", String.class, "address"));
        jdbcType.setValueFields(vals.toArray(new JdbcTypeField[vals.size()]));

        return jdbcType;
    }

    /**
     * Create SQL Query descriptor for person.
     *
     * @return Configured query entity.
     */
    private static QueryEntity queryEntityPerson() {
        QueryEntity qryEntity = new QueryEntity();

        qryEntity.setKeyType("ignite.models.PersonKey");
        qryEntity.setValueType("ignite.models.Person");

        // Query fields for person.
        LinkedHashMap<String, String> fields = new LinkedHashMap<>();

        fields.put("age", "java.lang.Integer");
        fields.put("name", "java.lang.String");
        fields.put("address", "java.lang.String");

        qryEntity.setFields(fields);

        return qryEntity;
    }

    /**
     * Configure cache.
     *
     * @param cacheName Cache name.
     * @param storeFactory Cache store factory.
     * @return Cache configuration.
     */
    public static <K, V> CacheConfiguration<K, V> cache(String cacheName, CacheJdbcPojoStoreFactory<K, V> storeFactory) {  	
    	DriverManagerDataSource dataSource=new DriverManagerDataSource("jdbc:mysql://localhost:3306/ignite", "root", "123456");
		dataSource.setDriverClassName("com.mysql.jdbc.Driver");
    	
    	
        if (storeFactory == null)
             throw new IllegalArgumentException("Cache store factory cannot be null.");

        CacheConfiguration<K, V> ccfg = new CacheConfiguration<>(cacheName);

        ccfg.setCacheStoreFactory(storeFactory);
        ccfg.setReadThrough(true);
        ccfg.setWriteThrough(true);
//ccfg.setWriteSynchronizationMode(CacheWriteSynchronizationMode.FULL_SYNC);
        // Configure JDBC types. 
        Collection<JdbcType> jdbcTypes = new ArrayList<>();

        jdbcTypes.add(jdbcTypePerson(cacheName));
        storeFactory.setDataSourceFactory(new DataSourceFactory<DataSource>());
        storeFactory.setTypes(jdbcTypes.toArray(new JdbcType[jdbcTypes.size()]));

        // Configure query entities. 
        Collection<QueryEntity> qryEntities = new ArrayList<>();

        qryEntities.add(queryEntityPerson());

        ccfg.setQueryEntities(qryEntities);

        return ccfg;
    }
}
