/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ignite.models;

import java.io.*;

/**
 * PersonKey definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 08/19/2016.
 */
public class PersonKey implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for age. */
    private Integer age;

    /**
     * Empty constructor.
     */
    public PersonKey() {
        // No-op.
    }

    /**
     * Full constructor.
     */
    public PersonKey(
    		Integer age
    ) {
        this.age = age;
    }

    /**
     * Gets age.
     *
     * @return Value for age.
     */
    public Integer getAge() {
        return age;
    }

    /**
     * Sets age.
     *
     * @param age New value for age.
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof PersonKey))
            return false;

        PersonKey that = (PersonKey)o;

        if (age != null ? !age.equals(that.age) : that.age != null)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = age != null ? age.hashCode() : 0;

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "PersonKey [age=" + age +
            "]";
    }
}

