/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package tpcw.bean;

import java.io.*;

/**
 * CcXacts definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 10/09/2016.
 */
public class CcXacts implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for cxOId. */
    private int cxOId;

    /** Value for cxType. */
    private String cxType;

    /** Value for cxNum. */
    private String cxNum;

    /** Value for cxName. */
    private String cxName;

    /** Value for cxExpire. */
    private java.sql.Date cxExpire;

    /** Value for cxAuthId. */
    private String cxAuthId;

    /** Value for cxXactAmt. */
    private Double cxXactAmt;

    /** Value for cxXactDate. */
    private java.sql.Date cxXactDate;

    /** Value for cxCoId. */
    private Integer cxCoId;

    /**
     * Empty constructor.
     */
    public CcXacts() {
        // No-op.
    }

    /**
     * Full constructor.
     */
    public CcXacts(
        int cxOId,
        String cxType,
        String cxNum,
        String cxName,
        java.sql.Date cxExpire,
        String cxAuthId,
        Double cxXactAmt,
        java.sql.Date cxXactDate,
        Integer cxCoId
    ) {
        this.cxOId = cxOId;
        this.cxType = cxType;
        this.cxNum = cxNum;
        this.cxName = cxName;
        this.cxExpire = cxExpire;
        this.cxAuthId = cxAuthId;
        this.cxXactAmt = cxXactAmt;
        this.cxXactDate = cxXactDate;
        this.cxCoId = cxCoId;
    }

    /**
     * Gets cxOId.
     *
     * @return Value for cxOId.
     */
    public int getCxOId() {
        return cxOId;
    }

    /**
     * Sets cxOId.
     *
     * @param cxOId New value for cxOId.
     */
    public void setCxOId(int cxOId) {
        this.cxOId = cxOId;
    }

    /**
     * Gets cxType.
     *
     * @return Value for cxType.
     */
    public String getCxType() {
        return cxType;
    }

    /**
     * Sets cxType.
     *
     * @param cxType New value for cxType.
     */
    public void setCxType(String cxType) {
        this.cxType = cxType;
    }

    /**
     * Gets cxNum.
     *
     * @return Value for cxNum.
     */
    public String getCxNum() {
        return cxNum;
    }

    /**
     * Sets cxNum.
     *
     * @param cxNum New value for cxNum.
     */
    public void setCxNum(String cxNum) {
        this.cxNum = cxNum;
    }

    /**
     * Gets cxName.
     *
     * @return Value for cxName.
     */
    public String getCxName() {
        return cxName;
    }

    /**
     * Sets cxName.
     *
     * @param cxName New value for cxName.
     */
    public void setCxName(String cxName) {
        this.cxName = cxName;
    }

    /**
     * Gets cxExpire.
     *
     * @return Value for cxExpire.
     */
    public java.sql.Date getCxExpire() {
        return cxExpire;
    }

    /**
     * Sets cxExpire.
     *
     * @param cxExpire New value for cxExpire.
     */
    public void setCxExpire(java.sql.Date cxExpire) {
        this.cxExpire = cxExpire;
    }

    /**
     * Gets cxAuthId.
     *
     * @return Value for cxAuthId.
     */
    public String getCxAuthId() {
        return cxAuthId;
    }

    /**
     * Sets cxAuthId.
     *
     * @param cxAuthId New value for cxAuthId.
     */
    public void setCxAuthId(String cxAuthId) {
        this.cxAuthId = cxAuthId;
    }

    /**
     * Gets cxXactAmt.
     *
     * @return Value for cxXactAmt.
     */
    public Double getCxXactAmt() {
        return cxXactAmt;
    }

    /**
     * Sets cxXactAmt.
     *
     * @param cxXactAmt New value for cxXactAmt.
     */
    public void setCxXactAmt(Double cxXactAmt) {
        this.cxXactAmt = cxXactAmt;
    }

    /**
     * Gets cxXactDate.
     *
     * @return Value for cxXactDate.
     */
    public java.sql.Date getCxXactDate() {
        return cxXactDate;
    }

    /**
     * Sets cxXactDate.
     *
     * @param cxXactDate New value for cxXactDate.
     */
    public void setCxXactDate(java.sql.Date cxXactDate) {
        this.cxXactDate = cxXactDate;
    }

    /**
     * Gets cxCoId.
     *
     * @return Value for cxCoId.
     */
    public Integer getCxCoId() {
        return cxCoId;
    }

    /**
     * Sets cxCoId.
     *
     * @param cxCoId New value for cxCoId.
     */
    public void setCxCoId(Integer cxCoId) {
        this.cxCoId = cxCoId;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof CcXacts))
            return false;

        CcXacts that = (CcXacts)o;

        if (cxOId != that.cxOId)
            return false;

        if (cxType != null ? !cxType.equals(that.cxType) : that.cxType != null)
            return false;

        if (cxNum != null ? !cxNum.equals(that.cxNum) : that.cxNum != null)
            return false;

        if (cxName != null ? !cxName.equals(that.cxName) : that.cxName != null)
            return false;

        if (cxExpire != null ? !cxExpire.equals(that.cxExpire) : that.cxExpire != null)
            return false;

        if (cxAuthId != null ? !cxAuthId.equals(that.cxAuthId) : that.cxAuthId != null)
            return false;

        if (cxXactAmt != null ? !cxXactAmt.equals(that.cxXactAmt) : that.cxXactAmt != null)
            return false;

        if (cxXactDate != null ? !cxXactDate.equals(that.cxXactDate) : that.cxXactDate != null)
            return false;

        if (cxCoId != null ? !cxCoId.equals(that.cxCoId) : that.cxCoId != null)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = cxOId;

        res = 31 * res + (cxType != null ? cxType.hashCode() : 0);

        res = 31 * res + (cxNum != null ? cxNum.hashCode() : 0);

        res = 31 * res + (cxName != null ? cxName.hashCode() : 0);

        res = 31 * res + (cxExpire != null ? cxExpire.hashCode() : 0);

        res = 31 * res + (cxAuthId != null ? cxAuthId.hashCode() : 0);

        res = 31 * res + (cxXactAmt != null ? cxXactAmt.hashCode() : 0);

        res = 31 * res + (cxXactDate != null ? cxXactDate.hashCode() : 0);

        res = 31 * res + (cxCoId != null ? cxCoId.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "CcXacts [cxOId=" + cxOId +
            ", cxType=" + cxType +
            ", cxNum=" + cxNum +
            ", cxName=" + cxName +
            ", cxExpire=" + cxExpire +
            ", cxAuthId=" + cxAuthId +
            ", cxXactAmt=" + cxXactAmt +
            ", cxXactDate=" + cxXactDate +
            ", cxCoId=" + cxCoId +
            "]";
    }
}

