/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package tpcw.bean;

import java.io.*;

/**
 * CcXactsKey definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 10/09/2016.
 */
public class CcXactsKey implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for cxOId. */
    private int cxOId;

    /**
     * Empty constructor.
     */
    public CcXactsKey() {
        // No-op.
    }

    /**
     * Full constructor.
     */
    public CcXactsKey(
        int cxOId
    ) {
        this.cxOId = cxOId;
    }

    /**
     * Gets cxOId.
     *
     * @return Value for cxOId.
     */
    public int getCxOId() {
        return cxOId;
    }

    /**
     * Sets cxOId.
     *
     * @param cxOId New value for cxOId.
     */
    public void setCxOId(int cxOId) {
        this.cxOId = cxOId;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof CcXactsKey))
            return false;

        CcXactsKey that = (CcXactsKey)o;

        if (cxOId != that.cxOId)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = cxOId;

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "CcXactsKey [cxOId=" + cxOId +
            "]";
    }
}

