/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package tpcw.bean;

import java.io.*;

/**
 * Country definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 10/09/2016.
 */
public class Country implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for coId. */
    private int coId;

    /** Value for coName. */
    private String coName;

    /** Value for coExchange. */
    private Double coExchange;

    /** Value for coCurrency. */
    private String coCurrency;

    /**
     * Empty constructor.
     */
    public Country() {
        // No-op.
    }

    /**
     * Full constructor.
     */
    public Country(
        int coId,
        String coName,
        Double coExchange,
        String coCurrency
    ) {
        this.coId = coId;
        this.coName = coName;
        this.coExchange = coExchange;
        this.coCurrency = coCurrency;
    }

    /**
     * Gets coId.
     *
     * @return Value for coId.
     */
    public int getCoId() {
        return coId;
    }

    /**
     * Sets coId.
     *
     * @param coId New value for coId.
     */
    public void setCoId(int coId) {
        this.coId = coId;
    }

    /**
     * Gets coName.
     *
     * @return Value for coName.
     */
    public String getCoName() {
        return coName;
    }

    /**
     * Sets coName.
     *
     * @param coName New value for coName.
     */
    public void setCoName(String coName) {
        this.coName = coName;
    }

    /**
     * Gets coExchange.
     *
     * @return Value for coExchange.
     */
    public Double getCoExchange() {
        return coExchange;
    }

    /**
     * Sets coExchange.
     *
     * @param coExchange New value for coExchange.
     */
    public void setCoExchange(Double coExchange) {
        this.coExchange = coExchange;
    }

    /**
     * Gets coCurrency.
     *
     * @return Value for coCurrency.
     */
    public String getCoCurrency() {
        return coCurrency;
    }

    /**
     * Sets coCurrency.
     *
     * @param coCurrency New value for coCurrency.
     */
    public void setCoCurrency(String coCurrency) {
        this.coCurrency = coCurrency;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof Country))
            return false;

        Country that = (Country)o;

        if (coId != that.coId)
            return false;

        if (coName != null ? !coName.equals(that.coName) : that.coName != null)
            return false;

        if (coExchange != null ? !coExchange.equals(that.coExchange) : that.coExchange != null)
            return false;

        if (coCurrency != null ? !coCurrency.equals(that.coCurrency) : that.coCurrency != null)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = coId;

        res = 31 * res + (coName != null ? coName.hashCode() : 0);

        res = 31 * res + (coExchange != null ? coExchange.hashCode() : 0);

        res = 31 * res + (coCurrency != null ? coCurrency.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "Country [coId=" + coId +
            ", coName=" + coName +
            ", coExchange=" + coExchange +
            ", coCurrency=" + coCurrency +
            "]";
    }
}

