/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package tpcw.bean;

import java.io.*;

/**
 * Customer definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 10/09/2016.
 */
public class Customer implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for cId. */
    private int cId;

    /** Value for cUname. */
    private String cUname;

    /** Value for cPasswd. */
    private String cPasswd;

    /** Value for cFname. */
    private String cFname;

    /** Value for cLname. */
    private String cLname;

    /** Value for cAddrId. */
    private Integer cAddrId;

    /** Value for cPhone. */
    private String cPhone;

    /** Value for cEmail. */
    private String cEmail;

    /** Value for cSince. */
    private java.sql.Date cSince;

    /** Value for cLastLogin. */
    private java.sql.Date cLastLogin;

    /** Value for cLogin. */
    private java.sql.Timestamp cLogin;

    /** Value for cExpiration. */
    private java.sql.Timestamp cExpiration;

    /** Value for cDiscount. */
    private Double cDiscount;

    /** Value for cBalance. */
    private Double cBalance;

    /** Value for cYtdPmt. */
    private Double cYtdPmt;

    /** Value for cBirthdate. */
    private java.sql.Date cBirthdate;

    /** Value for cData. */
    private String cData;

    /**
     * Empty constructor.
     */
    public Customer() {
        // No-op.
    }

    /**
     * Full constructor.
     */
    public Customer(
        int cId,
        String cUname,
        String cPasswd,
        String cFname,
        String cLname,
        Integer cAddrId,
        String cPhone,
        String cEmail,
        java.sql.Date cSince,
        java.sql.Date cLastLogin,
        java.sql.Timestamp cLogin,
        java.sql.Timestamp cExpiration,
        Double cDiscount,
        Double cBalance,
        Double cYtdPmt,
        java.sql.Date cBirthdate,
        String cData
    ) {
        this.cId = cId;
        this.cUname = cUname;
        this.cPasswd = cPasswd;
        this.cFname = cFname;
        this.cLname = cLname;
        this.cAddrId = cAddrId;
        this.cPhone = cPhone;
        this.cEmail = cEmail;
        this.cSince = cSince;
        this.cLastLogin = cLastLogin;
        this.cLogin = cLogin;
        this.cExpiration = cExpiration;
        this.cDiscount = cDiscount;
        this.cBalance = cBalance;
        this.cYtdPmt = cYtdPmt;
        this.cBirthdate = cBirthdate;
        this.cData = cData;
    }

    /**
     * Gets cId.
     *
     * @return Value for cId.
     */
    public int getCId() {
        return cId;
    }

    /**
     * Sets cId.
     *
     * @param cId New value for cId.
     */
    public void setCId(int cId) {
        this.cId = cId;
    }

    /**
     * Gets cUname.
     *
     * @return Value for cUname.
     */
    public String getCUname() {
        return cUname;
    }

    /**
     * Sets cUname.
     *
     * @param cUname New value for cUname.
     */
    public void setCUname(String cUname) {
        this.cUname = cUname;
    }

    /**
     * Gets cPasswd.
     *
     * @return Value for cPasswd.
     */
    public String getCPasswd() {
        return cPasswd;
    }

    /**
     * Sets cPasswd.
     *
     * @param cPasswd New value for cPasswd.
     */
    public void setCPasswd(String cPasswd) {
        this.cPasswd = cPasswd;
    }

    /**
     * Gets cFname.
     *
     * @return Value for cFname.
     */
    public String getCFname() {
        return cFname;
    }

    /**
     * Sets cFname.
     *
     * @param cFname New value for cFname.
     */
    public void setCFname(String cFname) {
        this.cFname = cFname;
    }

    /**
     * Gets cLname.
     *
     * @return Value for cLname.
     */
    public String getCLname() {
        return cLname;
    }

    /**
     * Sets cLname.
     *
     * @param cLname New value for cLname.
     */
    public void setCLname(String cLname) {
        this.cLname = cLname;
    }

    /**
     * Gets cAddrId.
     *
     * @return Value for cAddrId.
     */
    public Integer getCAddrId() {
        return cAddrId;
    }

    /**
     * Sets cAddrId.
     *
     * @param cAddrId New value for cAddrId.
     */
    public void setCAddrId(Integer cAddrId) {
        this.cAddrId = cAddrId;
    }

    /**
     * Gets cPhone.
     *
     * @return Value for cPhone.
     */
    public String getCPhone() {
        return cPhone;
    }

    /**
     * Sets cPhone.
     *
     * @param cPhone New value for cPhone.
     */
    public void setCPhone(String cPhone) {
        this.cPhone = cPhone;
    }

    /**
     * Gets cEmail.
     *
     * @return Value for cEmail.
     */
    public String getCEmail() {
        return cEmail;
    }

    /**
     * Sets cEmail.
     *
     * @param cEmail New value for cEmail.
     */
    public void setCEmail(String cEmail) {
        this.cEmail = cEmail;
    }

    /**
     * Gets cSince.
     *
     * @return Value for cSince.
     */
    public java.sql.Date getCSince() {
        return cSince;
    }

    /**
     * Sets cSince.
     *
     * @param cSince New value for cSince.
     */
    public void setCSince(java.sql.Date cSince) {
        this.cSince = cSince;
    }

    /**
     * Gets cLastLogin.
     *
     * @return Value for cLastLogin.
     */
    public java.sql.Date getCLastLogin() {
        return cLastLogin;
    }

    /**
     * Sets cLastLogin.
     *
     * @param cLastLogin New value for cLastLogin.
     */
    public void setCLastLogin(java.sql.Date cLastLogin) {
        this.cLastLogin = cLastLogin;
    }

    /**
     * Gets cLogin.
     *
     * @return Value for cLogin.
     */
    public java.sql.Timestamp getCLogin() {
        return cLogin;
    }

    /**
     * Sets cLogin.
     *
     * @param cLogin New value for cLogin.
     */
    public void setCLogin(java.sql.Timestamp cLogin) {
        this.cLogin = cLogin;
    }

    /**
     * Gets cExpiration.
     *
     * @return Value for cExpiration.
     */
    public java.sql.Timestamp getCExpiration() {
        return cExpiration;
    }

    /**
     * Sets cExpiration.
     *
     * @param cExpiration New value for cExpiration.
     */
    public void setCExpiration(java.sql.Timestamp cExpiration) {
        this.cExpiration = cExpiration;
    }

    /**
     * Gets cDiscount.
     *
     * @return Value for cDiscount.
     */
    public Double getCDiscount() {
        return cDiscount;
    }

    /**
     * Sets cDiscount.
     *
     * @param cDiscount New value for cDiscount.
     */
    public void setCDiscount(Double cDiscount) {
        this.cDiscount = cDiscount;
    }

    /**
     * Gets cBalance.
     *
     * @return Value for cBalance.
     */
    public Double getCBalance() {
        return cBalance;
    }

    /**
     * Sets cBalance.
     *
     * @param cBalance New value for cBalance.
     */
    public void setCBalance(Double cBalance) {
        this.cBalance = cBalance;
    }

    /**
     * Gets cYtdPmt.
     *
     * @return Value for cYtdPmt.
     */
    public Double getCYtdPmt() {
        return cYtdPmt;
    }

    /**
     * Sets cYtdPmt.
     *
     * @param cYtdPmt New value for cYtdPmt.
     */
    public void setCYtdPmt(Double cYtdPmt) {
        this.cYtdPmt = cYtdPmt;
    }

    /**
     * Gets cBirthdate.
     *
     * @return Value for cBirthdate.
     */
    public java.sql.Date getCBirthdate() {
        return cBirthdate;
    }

    /**
     * Sets cBirthdate.
     *
     * @param cBirthdate New value for cBirthdate.
     */
    public void setCBirthdate(java.sql.Date cBirthdate) {
        this.cBirthdate = cBirthdate;
    }

    /**
     * Gets cData.
     *
     * @return Value for cData.
     */
    public String getCData() {
        return cData;
    }

    /**
     * Sets cData.
     *
     * @param cData New value for cData.
     */
    public void setCData(String cData) {
        this.cData = cData;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof Customer))
            return false;

        Customer that = (Customer)o;

        if (cId != that.cId)
            return false;

        if (cUname != null ? !cUname.equals(that.cUname) : that.cUname != null)
            return false;

        if (cPasswd != null ? !cPasswd.equals(that.cPasswd) : that.cPasswd != null)
            return false;

        if (cFname != null ? !cFname.equals(that.cFname) : that.cFname != null)
            return false;

        if (cLname != null ? !cLname.equals(that.cLname) : that.cLname != null)
            return false;

        if (cAddrId != null ? !cAddrId.equals(that.cAddrId) : that.cAddrId != null)
            return false;

        if (cPhone != null ? !cPhone.equals(that.cPhone) : that.cPhone != null)
            return false;

        if (cEmail != null ? !cEmail.equals(that.cEmail) : that.cEmail != null)
            return false;

        if (cSince != null ? !cSince.equals(that.cSince) : that.cSince != null)
            return false;

        if (cLastLogin != null ? !cLastLogin.equals(that.cLastLogin) : that.cLastLogin != null)
            return false;

        if (cLogin != null ? !cLogin.equals(that.cLogin) : that.cLogin != null)
            return false;

        if (cExpiration != null ? !cExpiration.equals(that.cExpiration) : that.cExpiration != null)
            return false;

        if (cDiscount != null ? !cDiscount.equals(that.cDiscount) : that.cDiscount != null)
            return false;

        if (cBalance != null ? !cBalance.equals(that.cBalance) : that.cBalance != null)
            return false;

        if (cYtdPmt != null ? !cYtdPmt.equals(that.cYtdPmt) : that.cYtdPmt != null)
            return false;

        if (cBirthdate != null ? !cBirthdate.equals(that.cBirthdate) : that.cBirthdate != null)
            return false;

        if (cData != null ? !cData.equals(that.cData) : that.cData != null)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = cId;

        res = 31 * res + (cUname != null ? cUname.hashCode() : 0);

        res = 31 * res + (cPasswd != null ? cPasswd.hashCode() : 0);

        res = 31 * res + (cFname != null ? cFname.hashCode() : 0);

        res = 31 * res + (cLname != null ? cLname.hashCode() : 0);

        res = 31 * res + (cAddrId != null ? cAddrId.hashCode() : 0);

        res = 31 * res + (cPhone != null ? cPhone.hashCode() : 0);

        res = 31 * res + (cEmail != null ? cEmail.hashCode() : 0);

        res = 31 * res + (cSince != null ? cSince.hashCode() : 0);

        res = 31 * res + (cLastLogin != null ? cLastLogin.hashCode() : 0);

        res = 31 * res + (cLogin != null ? cLogin.hashCode() : 0);

        res = 31 * res + (cExpiration != null ? cExpiration.hashCode() : 0);

        res = 31 * res + (cDiscount != null ? cDiscount.hashCode() : 0);

        res = 31 * res + (cBalance != null ? cBalance.hashCode() : 0);

        res = 31 * res + (cYtdPmt != null ? cYtdPmt.hashCode() : 0);

        res = 31 * res + (cBirthdate != null ? cBirthdate.hashCode() : 0);

        res = 31 * res + (cData != null ? cData.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "Customer [cId=" + cId +
            ", cUname=" + cUname +
            ", cPasswd=" + cPasswd +
            ", cFname=" + cFname +
            ", cLname=" + cLname +
            ", cAddrId=" + cAddrId +
            ", cPhone=" + cPhone +
            ", cEmail=" + cEmail +
            ", cSince=" + cSince +
            ", cLastLogin=" + cLastLogin +
            ", cLogin=" + cLogin +
            ", cExpiration=" + cExpiration +
            ", cDiscount=" + cDiscount +
            ", cBalance=" + cBalance +
            ", cYtdPmt=" + cYtdPmt +
            ", cBirthdate=" + cBirthdate +
            ", cData=" + cData +
            "]";
    }
}

