/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package tpcw.bean;

import java.io.*;

/**
 * OrderLineKey definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 10/09/2016.
 */
public class OrderLineKey implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for olId. */
    private int olId;

    /** Value for olOId. */
    private int olOId;

    /**
     * Empty constructor.
     */
    public OrderLineKey() {
        // No-op.
    }

    /**
     * Full constructor.
     */
    public OrderLineKey(
        int olId,
        int olOId
    ) {
        this.olId = olId;
        this.olOId = olOId;
    }

    /**
     * Gets olId.
     *
     * @return Value for olId.
     */
    public int getOlId() {
        return olId;
    }

    /**
     * Sets olId.
     *
     * @param olId New value for olId.
     */
    public void setOlId(int olId) {
        this.olId = olId;
    }

    /**
     * Gets olOId.
     *
     * @return Value for olOId.
     */
    public int getOlOId() {
        return olOId;
    }

    /**
     * Sets olOId.
     *
     * @param olOId New value for olOId.
     */
    public void setOlOId(int olOId) {
        this.olOId = olOId;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof OrderLineKey))
            return false;

        OrderLineKey that = (OrderLineKey)o;

        if (olId != that.olId)
            return false;

        if (olOId != that.olOId)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = olId;

        res = 31 * res + olOId;

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "OrderLineKey [olId=" + olId +
            ", olOId=" + olOId +
            "]";
    }
}

