/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package tpcw.bean;

import java.io.*;

/**
 * Orders definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 10/09/2016.
 */
public class Orders implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for oId. */
    private int oId;

    /** Value for oCId. */
    private Integer oCId;

    /** Value for oDate. */
    private java.sql.Date oDate;

    /** Value for oSubTotal. */
    private Double oSubTotal;

    /** Value for oTax. */
    private Double oTax;

    /** Value for oTotal. */
    private Double oTotal;

    /** Value for oShipType. */
    private String oShipType;

    /** Value for oShipDate. */
    private java.sql.Date oShipDate;

    /** Value for oBillAddrId. */
    private Integer oBillAddrId;

    /** Value for oShipAddrId. */
    private Integer oShipAddrId;

    /** Value for oStatus. */
    private String oStatus;

    /**
     * Empty constructor.
     */
    public Orders() {
        // No-op.
    }

    /**
     * Full constructor.
     */
    public Orders(
        int oId,
        Integer oCId,
        java.sql.Date oDate,
        Double oSubTotal,
        Double oTax,
        Double oTotal,
        String oShipType,
        java.sql.Date oShipDate,
        Integer oBillAddrId,
        Integer oShipAddrId,
        String oStatus
    ) {
        this.oId = oId;
        this.oCId = oCId;
        this.oDate = oDate;
        this.oSubTotal = oSubTotal;
        this.oTax = oTax;
        this.oTotal = oTotal;
        this.oShipType = oShipType;
        this.oShipDate = oShipDate;
        this.oBillAddrId = oBillAddrId;
        this.oShipAddrId = oShipAddrId;
        this.oStatus = oStatus;
    }

    /**
     * Gets oId.
     *
     * @return Value for oId.
     */
    public int getOId() {
        return oId;
    }

    /**
     * Sets oId.
     *
     * @param oId New value for oId.
     */
    public void setOId(int oId) {
        this.oId = oId;
    }

    /**
     * Gets oCId.
     *
     * @return Value for oCId.
     */
    public Integer getOCId() {
        return oCId;
    }

    /**
     * Sets oCId.
     *
     * @param oCId New value for oCId.
     */
    public void setOCId(Integer oCId) {
        this.oCId = oCId;
    }

    /**
     * Gets oDate.
     *
     * @return Value for oDate.
     */
    public java.sql.Date getODate() {
        return oDate;
    }

    /**
     * Sets oDate.
     *
     * @param oDate New value for oDate.
     */
    public void setODate(java.sql.Date oDate) {
        this.oDate = oDate;
    }

    /**
     * Gets oSubTotal.
     *
     * @return Value for oSubTotal.
     */
    public Double getOSubTotal() {
        return oSubTotal;
    }

    /**
     * Sets oSubTotal.
     *
     * @param oSubTotal New value for oSubTotal.
     */
    public void setOSubTotal(Double oSubTotal) {
        this.oSubTotal = oSubTotal;
    }

    /**
     * Gets oTax.
     *
     * @return Value for oTax.
     */
    public Double getOTax() {
        return oTax;
    }

    /**
     * Sets oTax.
     *
     * @param oTax New value for oTax.
     */
    public void setOTax(Double oTax) {
        this.oTax = oTax;
    }

    /**
     * Gets oTotal.
     *
     * @return Value for oTotal.
     */
    public Double getOTotal() {
        return oTotal;
    }

    /**
     * Sets oTotal.
     *
     * @param oTotal New value for oTotal.
     */
    public void setOTotal(Double oTotal) {
        this.oTotal = oTotal;
    }

    /**
     * Gets oShipType.
     *
     * @return Value for oShipType.
     */
    public String getOShipType() {
        return oShipType;
    }

    /**
     * Sets oShipType.
     *
     * @param oShipType New value for oShipType.
     */
    public void setOShipType(String oShipType) {
        this.oShipType = oShipType;
    }

    /**
     * Gets oShipDate.
     *
     * @return Value for oShipDate.
     */
    public java.sql.Date getOShipDate() {
        return oShipDate;
    }

    /**
     * Sets oShipDate.
     *
     * @param oShipDate New value for oShipDate.
     */
    public void setOShipDate(java.sql.Date oShipDate) {
        this.oShipDate = oShipDate;
    }

    /**
     * Gets oBillAddrId.
     *
     * @return Value for oBillAddrId.
     */
    public Integer getOBillAddrId() {
        return oBillAddrId;
    }

    /**
     * Sets oBillAddrId.
     *
     * @param oBillAddrId New value for oBillAddrId.
     */
    public void setOBillAddrId(Integer oBillAddrId) {
        this.oBillAddrId = oBillAddrId;
    }

    /**
     * Gets oShipAddrId.
     *
     * @return Value for oShipAddrId.
     */
    public Integer getOShipAddrId() {
        return oShipAddrId;
    }

    /**
     * Sets oShipAddrId.
     *
     * @param oShipAddrId New value for oShipAddrId.
     */
    public void setOShipAddrId(Integer oShipAddrId) {
        this.oShipAddrId = oShipAddrId;
    }

    /**
     * Gets oStatus.
     *
     * @return Value for oStatus.
     */
    public String getOStatus() {
        return oStatus;
    }

    /**
     * Sets oStatus.
     *
     * @param oStatus New value for oStatus.
     */
    public void setOStatus(String oStatus) {
        this.oStatus = oStatus;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof Orders))
            return false;

        Orders that = (Orders)o;

        if (oId != that.oId)
            return false;

        if (oCId != null ? !oCId.equals(that.oCId) : that.oCId != null)
            return false;

        if (oDate != null ? !oDate.equals(that.oDate) : that.oDate != null)
            return false;

        if (oSubTotal != null ? !oSubTotal.equals(that.oSubTotal) : that.oSubTotal != null)
            return false;

        if (oTax != null ? !oTax.equals(that.oTax) : that.oTax != null)
            return false;

        if (oTotal != null ? !oTotal.equals(that.oTotal) : that.oTotal != null)
            return false;

        if (oShipType != null ? !oShipType.equals(that.oShipType) : that.oShipType != null)
            return false;

        if (oShipDate != null ? !oShipDate.equals(that.oShipDate) : that.oShipDate != null)
            return false;

        if (oBillAddrId != null ? !oBillAddrId.equals(that.oBillAddrId) : that.oBillAddrId != null)
            return false;

        if (oShipAddrId != null ? !oShipAddrId.equals(that.oShipAddrId) : that.oShipAddrId != null)
            return false;

        if (oStatus != null ? !oStatus.equals(that.oStatus) : that.oStatus != null)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = oId;

        res = 31 * res + (oCId != null ? oCId.hashCode() : 0);

        res = 31 * res + (oDate != null ? oDate.hashCode() : 0);

        res = 31 * res + (oSubTotal != null ? oSubTotal.hashCode() : 0);

        res = 31 * res + (oTax != null ? oTax.hashCode() : 0);

        res = 31 * res + (oTotal != null ? oTotal.hashCode() : 0);

        res = 31 * res + (oShipType != null ? oShipType.hashCode() : 0);

        res = 31 * res + (oShipDate != null ? oShipDate.hashCode() : 0);

        res = 31 * res + (oBillAddrId != null ? oBillAddrId.hashCode() : 0);

        res = 31 * res + (oShipAddrId != null ? oShipAddrId.hashCode() : 0);

        res = 31 * res + (oStatus != null ? oStatus.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "Orders [oId=" + oId +
            ", oCId=" + oCId +
            ", oDate=" + oDate +
            ", oSubTotal=" + oSubTotal +
            ", oTax=" + oTax +
            ", oTotal=" + oTotal +
            ", oShipType=" + oShipType +
            ", oShipDate=" + oShipDate +
            ", oBillAddrId=" + oBillAddrId +
            ", oShipAddrId=" + oShipAddrId +
            ", oStatus=" + oStatus +
            "]";
    }
}

