/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package tpcw.bean;

import java.io.*;

/**
 * OrderLine definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 10/09/2016.
 */
public class OrderLine implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for olId. */
    private int olId;

    /** Value for olOId. */
    private int olOId;

    /** Value for olIId. */
    private Integer olIId;

    /** Value for olQty. */
    private Integer olQty;

    /** Value for olDiscount. */
    private Double olDiscount;

    /** Value for olComments. */
    private String olComments;

    /**
     * Empty constructor.
     */
    public OrderLine() {
        // No-op.
    }

    /**
     * Full constructor.
     */
    public OrderLine(
        int olId,
        int olOId,
        Integer olIId,
        Integer olQty,
        Double olDiscount,
        String olComments
    ) {
        this.olId = olId;
        this.olOId = olOId;
        this.olIId = olIId;
        this.olQty = olQty;
        this.olDiscount = olDiscount;
        this.olComments = olComments;
    }

    /**
     * Gets olId.
     *
     * @return Value for olId.
     */
    public int getOlId() {
        return olId;
    }

    /**
     * Sets olId.
     *
     * @param olId New value for olId.
     */
    public void setOlId(int olId) {
        this.olId = olId;
    }

    /**
     * Gets olOId.
     *
     * @return Value for olOId.
     */
    public int getOlOId() {
        return olOId;
    }

    /**
     * Sets olOId.
     *
     * @param olOId New value for olOId.
     */
    public void setOlOId(int olOId) {
        this.olOId = olOId;
    }

    /**
     * Gets olIId.
     *
     * @return Value for olIId.
     */
    public Integer getOlIId() {
        return olIId;
    }

    /**
     * Sets olIId.
     *
     * @param olIId New value for olIId.
     */
    public void setOlIId(Integer olIId) {
        this.olIId = olIId;
    }

    /**
     * Gets olQty.
     *
     * @return Value for olQty.
     */
    public Integer getOlQty() {
        return olQty;
    }

    /**
     * Sets olQty.
     *
     * @param olQty New value for olQty.
     */
    public void setOlQty(Integer olQty) {
        this.olQty = olQty;
    }

    /**
     * Gets olDiscount.
     *
     * @return Value for olDiscount.
     */
    public Double getOlDiscount() {
        return olDiscount;
    }

    /**
     * Sets olDiscount.
     *
     * @param olDiscount New value for olDiscount.
     */
    public void setOlDiscount(Double olDiscount) {
        this.olDiscount = olDiscount;
    }

    /**
     * Gets olComments.
     *
     * @return Value for olComments.
     */
    public String getOlComments() {
        return olComments;
    }

    /**
     * Sets olComments.
     *
     * @param olComments New value for olComments.
     */
    public void setOlComments(String olComments) {
        this.olComments = olComments;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof OrderLine))
            return false;

        OrderLine that = (OrderLine)o;

        if (olId != that.olId)
            return false;

        if (olOId != that.olOId)
            return false;

        if (olIId != null ? !olIId.equals(that.olIId) : that.olIId != null)
            return false;

        if (olQty != null ? !olQty.equals(that.olQty) : that.olQty != null)
            return false;

        if (olDiscount != null ? !olDiscount.equals(that.olDiscount) : that.olDiscount != null)
            return false;

        if (olComments != null ? !olComments.equals(that.olComments) : that.olComments != null)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = olId;

        res = 31 * res + olOId;

        res = 31 * res + (olIId != null ? olIId.hashCode() : 0);

        res = 31 * res + (olQty != null ? olQty.hashCode() : 0);

        res = 31 * res + (olDiscount != null ? olDiscount.hashCode() : 0);

        res = 31 * res + (olComments != null ? olComments.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "OrderLine [olId=" + olId +
            ", olOId=" + olOId +
            ", olIId=" + olIId +
            ", olQty=" + olQty +
            ", olDiscount=" + olDiscount +
            ", olComments=" + olComments +
            "]";
    }
}

