/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package tpcw.bean;

import java.io.*;

/**
 * ShoppingCartKey definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 10/09/2016.
 */
public class ShoppingCartKey implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for scId. */
    private int scId;

    /**
     * Empty constructor.
     */
    public ShoppingCartKey() {
        // No-op.
    }

    /**
     * Full constructor.
     */
    public ShoppingCartKey(
        int scId
    ) {
        this.scId = scId;
    }

    /**
     * Gets scId.
     *
     * @return Value for scId.
     */
    public int getScId() {
        return scId;
    }

    /**
     * Sets scId.
     *
     * @param scId New value for scId.
     */
    public void setScId(int scId) {
        this.scId = scId;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof ShoppingCartKey))
            return false;

        ShoppingCartKey that = (ShoppingCartKey)o;

        if (scId != that.scId)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = scId;

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "ShoppingCartKey [scId=" + scId +
            "]";
    }
}

